### ISSUE TITLE
Time output error

### ISSUE THREAD

**Issue by samnatale** [rcackerman/notice-of-claim#13]
When the time of the incident has a 0 in the minutes, the 0 is dropped. So 7:03 --> 7:3.

**Comment by rcackerman** [comment]
Hey @samnatale - thanks for submitting issues! Where is the 0 being dropped? Is it in the docx or elsewhere?

**Comment by rcackerman** [comment]
@samnatale This should be fixed by 4f6e1d836e3b7afb28016ba6b93a8a1d56c00fcb, but feel free to reopen if it isn't.
