### ISSUE TITLE
Improper output for series of damaged/taken objects.

### ISSUE THREAD

**Issue by samnatale** [rcackerman/notice-of-claim#15]
When two objects are specified as being damaged or taken, an unecessary "and" appears after the series instead of within it. For instance "Claimant’s property, to wit a wallet, a car, and , was taken."

**Comment by rcackerman** [comment]
@samnatale - What was the url for the notice you created? I want to check something in the database.

**Comment by rcackerman** [comment]
@samnatale - Nevermind. Figured out the problem.

**Comment by rcackerman** [comment]
@samnatale Can you check this and make sure it works for you? Please feel free to re-open the issue if you find this to still be a problem.
