### ISSUE TITLE
2x "claims"

### ISSUE THREAD

**Issue by jtashea** [rcackerman/notice-of-claim#19]
The word "claims" appears in repetition in the line starting "PLEASE TAKE NOTICE"

**Comment by rcackerman** [comment]
Can you copy-paste or let me know the report number where that's happening?

**Comment by jtashea** [comment]
![image](https://cloud.githubusercontent.com/assets/6961181/14318382/8f3add54-fbda-11e5-9ccc-b28f10a4e183.png)

**Comment by jtashea** [comment]
it was notice_2016-03-2214-26-29+0000

**Comment by rcackerman** [comment]
Can you try generating the letter again and let me know if this is fixed? I'm not able to reproduce it.

**Comment by jtashea** [comment]
It looks good to me.
